### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by bryglen** [kairosinc/Kairos-SDK-PHP#1]
No composer support?

**Comment by ympons** [comment]
This project is a little primitive (IMHO ;-) ). For this reason I created a new PHP client for the Kairos Facial Recognition API https://github.com/ympons/PhpKairos

**Comment by bryglen** [comment]
I move away in this version because the library is using poor technology and I'm creating my own API version of Kairos like no namespace support

**Comment by coleca** [comment]
Please check out the recently contributed alternative:  https://github.com/ympons/PhpKairos

---

Cole

**Comment by doutornet** [comment]
Dear all , how I configure rtsp or another stream from ip camera ?

**Comment by coleca** [comment]
Hi,

Processing streaming video is not possible using our API at this time.  We have alternative solutions available if you need to process streaming video.  Please contact sales@kairos.com to setup a demo.
